### ISSUE TITLE
Error in "completeReducer - Completer" example

### ISSUE THREAD

**Issue by gabrielizalo** [Wolox/redux-recompose#25]
In the example of [completeReducer - Completer](https://github.com/Wolox/redux-recompose/blob/master/src/completers/completeReducer/docs.md) are missing:

- The initialState
- Change

`const reducer = createReducer(completeReducer(reducerDescription));`

for

`const reducer = createReducer(initialState, completeReducer(reducerDescription));`

Thanks,

**Comment by marianozicavo** [comment]
You're right. Do you want to make PR fixing it?

**Comment by gabrielizalo** [comment]
Of courseee 👍 

Another thing: why using docs.md and not readme.md?

Can I fix them too?

**Comment by marianozicavo** [comment]
Sure, that's just a convention we use. You can change it to readme if you want to.

**Comment by mvbattan** [comment]
Done in d604581
