### ISSUE TITLE
Error with withPreFetch folder

### ISSUE THREAD

**Issue by sfernandez11** [Wolox/redux-recompose#51]
After version 2.1.1 (2.1.1 and 2.1.2) there is a problem with the `withPreFetch` folder and that doesn't allow running the app.
The `index.js` file searchs for the `withPreFetch` folder but the name of the folder is `withPrefetch` (f not F) and that crash the app.
<img width="1678" alt="Captura de Pantalla 2019-04-18 a la(s) 18 55 09" src="https://user-images.githubusercontent.com/8583214/56394118-ab9f8a80-620c-11e9-9fe5-5ea9acb659d7.png">

Solution
Change the folder name to `withPreFetch`
<img width="1680" alt="Captura de Pantalla 2019-04-18 a la(s) 18 56 24" src="https://user-images.githubusercontent.com/8583214/56394123-b1956b80-620c-11e9-9dd1-26b9cec6d6fe.png">

**Comment by marianozicavo** [comment]
Thanks for reporting the issue!
The folder is actually called `withPreFetch`. Did this problem happen when you updated redux-recompose or on a fresh install?

**Comment by sfernandez11** [comment]
That's weird! I tested it in two ways (Wolmo and `react-native init + yarn add redux-recompose`, both fresh install) and I had the same result.
<img width="1678" alt="Captura de Pantalla 2019-04-22 a la(s) 16 31 31" src="https://user-images.githubusercontent.com/8583214/56521714-1b1ebe00-651c-11e9-869a-62fd1fab8be0.png">

**Comment by sfernandez11** [comment]
Resolved on `2.1.5` version
