### ISSUE TITLE
Error with babel-polyfill

### ISSUE THREAD

**Issue by nicolobruno** [Wolox/redux-recompose#9]
## Description
- Error when run with babel-polyfill version 6.26.0.

<img width="470" alt="captura de pantalla 2018-02-13 a la s 16 53 45" src="https://user-images.githubusercontent.com/28309103/36272684-0068fb52-1261-11e8-8890-d8435cc830f9.png">

Solution

Install 
pack
"devDependencies": {
    "babel-plugin-transform-runtime": "^6.23.0"
}

["transform-runtime", {
      "polyfill": false,
      "regenerator": true
    }]

**Comment by mvbattan** [comment]
@nicolobruno @hdf1986 This was solved by including `babel-polyfill` as a dependence:
https://github.com/Wolox/redux-recompose/commit/79030cc02bb3eb57e469547bfdab7a810cab479c
Thank you !
